// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /home/stoffe/dev/spark-wire/src/main/proto/proto.proto
package org.deephacks;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;

public final class Request extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_REQUESTID = 0;

  @ProtoField(tag = 1, type = UINT32)
  public final Integer requestId;

  public Request(Integer requestId) {
    this.requestId = requestId;
  }

  private Request(Builder builder) {
    this(builder.requestId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Request)) return false;
    return equals(requestId, ((Request) other).requestId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = requestId != null ? requestId.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<Request> {

    public Integer requestId;

    public Builder() {
    }

    public Builder(Request message) {
      super(message);
      if (message == null) return;
      this.requestId = message.requestId;
    }

    public Builder requestId(Integer requestId) {
      this.requestId = requestId;
      return this;
    }

    @Override
    public Request build() {
      return new Request(this);
    }
  }
}
